export const WORK_EXPERIENCES = {
  work0: {
    workTitle: "Sales Associate",
    workDescription:
      "In charge of selling on-site inventories and handling orders from offsite clients. Assists customers on their concerns regarding electronic surplus.",
    workLocation: "Mandaluyong City",
    companyName: "HMR Philippines",
    startYear: "2009",
    endYear: "2010",
    id: 0,
  },
  work1: {
    workTitle: "Web Host Specialist",
    workDescription:
      "Manages websites’ back-end applications that focuses on search engine optimization.",
    workLocation: "Remote Work - US based company",
    companyName: "Zeehan Host",
    startYear: "2011",
    endYear: "2011",
    id: 1,
  },
  work2: {
    workTitle: "Call Reviewer",
    workDescription:
      "A home-based job that analyzes and categorizes calls based on the guidelines given by the company. The calls are mainly about car dealerships which include buying, selling and renting cars.",
    workLocation: "Remote Work - US based company",
    companyName: "Callbox formerly Humanatic",
    startYear: "2011",
    endYear: "2018",
    id: 2,
  },
  work3: {
    workTitle: "Web Developer",
    workDescription: "",
    workDetails: [
      "Creating new feature for mobile application (React Native)",
      "Debugging the existing mobile application",
      "Creating new pages and feature for front-end (React JS) based on the specification given by Business Analyst and Graphic Artist",
      "Deploying Mobile application to Google play and deploying web based application using Google Cloud Platform",
    ],
    workLocation: "Mandaluyong City",
    companyName: "CTO Global Services",
    startYear: "August 2018",
    endYear: "2019",
    id: 3,
  },
  work4: {
    workTitle: "Senior Developer",
    workDescription: "",
    workDetails: [
      "Assisting in recruitment of new developers",
      "Code Reviews",
      "Manages tasks for junior developers",
      "Deploying and development of back end services such as microservices and APIs.",
    ],
    workLocation: "Mandaluyong City",
    companyName: "CTO Global Services",
    startYear: "2019",
    endYear: "2021",
    id: 4,
  },
  work5: {
    workTitle: "Full Stack Developer",
    workDescription: "",
    workDetails: [
      "Reviewing application requirements and interface designs",
      "Developing and implementing highly-responsive user interface components using React concepts",
      "Work with product team and graphic designers",
      "Design and implementation of low-latency, high-availability, and performant applications",
      "Development of Back end Node JS applications",
    ],
    workLocation: "Remote Work - US based Company",
    companyName: "Fulcrum",
    startYear: "March 2021",
    endYear: "December 2022",
    id: 5,
  },
};
